from pydantic import BaseModel, Field
from typing import Optional, List, Literal
from enum import Enum

from .base import DatabaseModel
from .tool_generation import ToolGenerationFailure
from .specs import UserToolRequirement


# ============================================================================
# Database Models (for MongoDB storage)
# ============================================================================

class JobStatus(str, Enum):
    """Job workflow status enumeration."""
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"


class Job(DatabaseModel):
    """Job for bulk tool generation workflow.

    A Job represents a user request to generate multiple tools.
    Each tool is generated by a separate Task.
    """

    job_id: str = Field(description="Short job identifier (e.g., job_abc123)")
    user_id: str = Field(description="User identifier")
    operation_type: Literal["generate", "update"] = Field(
        default="generate",
        description="Type of operation: generate new tools or update existing"
    )

    # Full request context
    tool_requirements: List[UserToolRequirement] = Field(
        default_factory=list,
        description="User tool requirements for generation"
    )

    status: JobStatus = Field(
        default=JobStatus.PENDING,
        description="Current job status"
    )

    # Task references (child tasks, one per tool)
    task_ids: List[str] = Field(
        default_factory=list,
        description="IDs of child tasks in the tasks collection"
    )

    # Atomic progress counters (updated by sessions)
    tools_completed: int = Field(
        default=0,
        description="Number of tools successfully completed"
    )
    tools_failed: int = Field(
        default=0,
        description="Number of tools that failed"
    )
    tools_in_progress: int = Field(
        default=0,
        description="Number of tools currently being processed"
    )

    error_message: Optional[str] = Field(
        default=None,
        description="Error message if job failed"
    )

    @property
    def total_tools(self) -> int:
        """Total number of tools to generate."""
        return len(self.tool_requirements)

    @property
    def is_complete(self) -> bool:
        """Check if all tools have been processed."""
        return (self.tools_completed + self.tools_failed) >= self.total_tools


# ============================================================================
# API Request/Response Models
# ============================================================================

class RequestMetadata(BaseModel):
    """Optional request metadata."""
    sessionId: Optional[str] = Field(None, description="Optional session tracking")
    clientId: Optional[str] = Field(None, description="Client identifier")


class ToolGenerationRequest(BaseModel):
    """Request model matching design spec."""
    toolRequirements: List[UserToolRequirement]
    metadata: Optional[RequestMetadata] = None


class JobProgress(BaseModel):
    """Job progress information."""
    total: int = Field(..., description="Total tools to generate")
    completed: int = Field(..., description="Successfully generated")
    failed: int = Field(..., description="Failed generations")
    inProgress: int = Field(..., description="Currently being generated")
    currentTool: Optional[str] = Field(None, description="Name of tool currently being generated")


class ToolFile(BaseModel):
    """Generated tool file information."""
    toolId: str = Field(..., description="Unique tool identifier")
    fileName: str = Field(..., description="e.g., 'calculate_molecular_weight.py'")
    filePath: str = Field(..., description="Full path to the file")
    description: str = Field(..., description="Tool description from requirement")
    code: str = Field(..., description="Generated Python code content")
    endpoint: Optional[str] = Field(None, description="SimpleTooling HTTP endpoint URL")
    registered: bool = Field(..., description="Whether registered with SimpleTooling")
    createdAt: str = Field(..., description="ISO timestamp")


class GenerationSummary(BaseModel):
    """Job completion summary."""
    totalRequested: int
    successful: int
    failed: int


class JobResponse(BaseModel):
    """Response model matching design spec."""
    jobId: str
    status: str  # 'pending' | 'running' | 'completed' | 'failed' | 'cancelled'
    createdAt: str  # ISO timestamp
    updatedAt: str  # ISO timestamp
    progress: JobProgress
    toolFiles: Optional[List[ToolFile]] = Field(None, description="Generated tool files (only when completed)")
    failures: Optional[List[ToolGenerationFailure]] = Field(None, description="Failed tool generations")
    summary: Optional[GenerationSummary] = Field(None, description="Job summary (only when completed)")
